### ISSUE TITLE
 lifecycle\cordova html page missing.....

### ISSUE THREAD

**Issue by cyciopes** [OnsenUI/onsen.io#467] opened 2017-09-30 06:02 UTC
Hi, Team. Some pages such as lifecycle\cordova are missing in Guide. I remember they exist before.

**Comment by asial-matagawa** [comment] 2017-10-02 06:08
Hi, @cyciopes!
It was caused by broken YAML codes and has been fixed in #468.
Thank you for reporting!

**Closed by asial-matagawa** 2017-10-02 06:08 UTC
